language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  # - rm -rf package-lock.json node_modules 
  - npm install coveralls
  - npm test -u 
after_success:
  - npm run coveralls