language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - rm -rf package-lock.json node_modules 
  - npm install
  - npm install coveralls
  - npm run test -- -u --coverage  
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN="OYLIKzD0XuXclVwb4fxEMMRdLhVM2X9TO" npm run coveralls
after_success:
  - npm coveralls